"""made some changes on the profile pic path

Revision ID: 6fbe88d34a7b
Revises: f8b57dc44611
Create Date: 2018-10-19 16:52:48.722402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbe88d34a7b'
down_revision = 'f8b57dc44611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_profile_pic_path_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_profile_pic_path_key', 'users', ['profile_pic_path'])
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
